name: Refactoring Proposal Form
description: Propose refactoring or typo fixing
labels: [refactoring]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this refactoring proposal!

  - type: textarea
    id: file
    attributes:
      label: File Location(s)
      description: Path to the file(s) to be refactored if any.
      placeholder: e.g. src/main.rs

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Please describe proposal details.
      placeholder: For example refer to the code snippets and describe what can be improved.
    validations:
      required: true
